version: '3.7'

services:
  chromadb:
    container_name: chromadb
    image: chromadb/chroma
    volumes:
        - ./data/chroma:/data
        #- /home/trout/work/llm/chroma-rag/data/chroma:/chroma/chroma
        
    ports:
        - '7230:8000' # <host port>:<container port>
    environment:
        IS_PERSISTENT: "true" 
        ANONYMIZED_TELEMETRY: "true" 
    restart: always

  chroma-rag:
    build: .
    container_name: chroma-rag
    links:
      - chromadb
    ports:
      - '3000:3000' # <host port>:<container port>
    restart: always
