version: '3.7'

services:
  chromadb:
    container_name: chromadb
    image: chromadb/chroma
    volumes:
        - ./data/chroma:/chroma/chroma
    ports:
        - '7230:8000' # <host port>:<container port>
    environment:
        IS_PERSISTENT: "true" 
        ANONYMIZED_TELEMETRY: "true" 